{% set version = "1.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-weights
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/weights_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/weights/weights_{{ version }}.tar.gz
  sha256: 6cc1c5020aad9d86cd38e65cad07958220f2f3e35e0e4bf81110c384be1599ea

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-hmisc
    - r-gdata
    - r-mice
  run:
    - r-base
    - r-hmisc
    - r-gdata
    - r-mice

test:
  commands:
    - $R -e "library('weights')"           # [not win]
    - "\"%R%\" -e \"library('weights')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=weights
  license: GPL-2.0-or-later
  summary: "Provides a variety of functions for producing simple weighted statistics, such as weighted Pearson's correlations, partial correlations, Chi-Squared statistics, histograms, and t-tests.  Also now includes some software for quickly recoding survey data and plotting point estimates from interaction terms in regressions
    (and multiply imputed regressions). NOTE: Weighted partial correlation calculations pulled to address a bug."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - tobiasraabe
